### ISSUE TITLE
.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node -e const net = require('net'); process.stdin.pause(); const client = net.createConnection({ host: '127.0.0.1', port: 37993 }, () => { client.pipe(process.stdout); process.stdin.pipe(client); }); client.on('close', function (hadError) { console.error(hadError ? 'Remote close with error' : 'Remote close'); process.exit(hadError ? 1 : 0); }); client.on('error', function (err) { process.stderr.write(err && (err.stack || err.message) || String(err)); });

### ISSUE THREAD

**Issue by zvailanu98** [microsoft/monaco-editor#4281]
.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node -e const net = require('net'); process.stdin.pause(); const client = net.createConnection({ host: '127.0.0.1', port: 37993 }, () => { client.pipe(process.stdout); process.stdin.pipe(client); }); client.on('close', function (hadError) { console.error(hadError ? 'Remote close with error' : 'Remote close'); process.exit(hadError ? 1 : 0); }); client.on('error', function (err) { process.stderr.write(err && (err.stack || err.message) || String(err)); });

_Originally posted by @zvailanu98 in https://github.com/microsoft/vscode/issues/199588#issuecomment-1832559142_
            
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/monaco-editor/issues/4114
- [ ] https://github.com/microsoft/monaco-editor/issues/4279
- [ ] https://github.com/microsoft/monaco-editor/issues/4277
```
